const fs = require('fs');
const path = require('path');

const src = path.join(__dirname, '../../worker/src/product_search/onboarding/prompts/onboard_v1.txt');
const dest = path.join(__dirname, '../lib/onboard/promptText.ts');

try {
  const text = fs.readFileSync(src, 'utf8');
  const code = `// AUTO-GENERATED by scripts/sync-prompt.js
// Do not edit this file directly. Edit onboard_v1.txt instead.
export const promptText = ${JSON.stringify(text)};
`;
  fs.writeFileSync(dest, code);
  console.log('[sync-prompt] Successfully synchronized onboard_v1.txt to promptText.ts');
} catch (err) {
  console.error('[sync-prompt] Failed to sync prompt:', err.message);
  process.exit(1);
}
