// AUTO-GENERATED by scripts/sync-prompt.js from worker/src/product_search/vendor_quirks.yaml.
// Do not edit directly — edit the YAML registry (ADR-068).

// Hosts (www-stripped) whose single-SKU products must carry BOTH a search URL
// and a page_type:"detail" URL — ADR-067 force_detail_backup enforcement.
export const FORCE_DETAIL_BACKUP_HOSTS: ReadonlySet<string> = new Set(["adorama.com","amazon.com","bestbuy.com","costco.com","crutchfield.com","gamestop.com","homedepot.com","lowes.com","macys.com","newegg.com","rei.com","sweetwater.com","target.com","walmart.com","williams-sonoma.com"]);

// Hosts (www-stripped) that AlterLab renders fine in production even when a
// bare datacenter fetch gets a 5xx / tiny body. Used by probe-url.ts to avoid
// false-negative demotions.
export const ALTERLAB_KNOWN_GOOD_HOSTS: ReadonlySet<string> = new Set(["amazon.com","bestbuy.com","ebay.com","target.com","walmart.com","williams-sonoma.com"]);

// Hosts (www-stripped) whose search-tile walker is blind, so the onboarder is
// told to PREFER page_type:"detail" URLs. ADR-079: a transient probe failure on
// such a vendor must NOT demote its detail URL — the runtime escalation ladder +
// circuit breaker (ADR-071/078) own retry; the registry says this vendor needs
// the detail URL, so the gate keeps it in `sources` with an advisory note.
export const PREFER_DETAIL_HOSTS: ReadonlySet<string> = new Set([]);
